//----------------------------------------------------------
// This function is the only function that's called.
// This strategy gives us better control of the page.
//----------------------------------------------------------
function doAll() {
  firebase.auth().onAuthStateChanged((user) => {
    if (user) {
      insertNameFromFirestore(user);
      getFavorites(user);
    } else {
      console.log("No user is signed in");
    }
  });
}
doAll();

//----------------------------------------------------------
// Wouldn't it be nice to see the User's Name on this page?
// Let's do it!  (Thinking ahead:  This function can be carved out,
// and put into script.js for other pages to use as well).
//----------------------------------------------------------//----------------------------------------------------------
function insertNameFromFirestore(user) {
  db.collection("users")
    .doc(user.uid)
    .get()
    .then((userDoc) => {
      console.log(userDoc.data().name);
      userName = userDoc.data().name;
      console.log(userName);
      document.getElementById("name-goes-here").innerHTML = userName;
    });
}

//----------------------------------------------------------
// This function takes input param User's Firestore document pointer
// and retrieves the "saved" array (of bookmarks)
// and dynamically displays them in the gallery
//----------------------------------------------------------
function getFavorites(user) {
  db.collection("users")
    .doc(user.uid)
    .get()
    .then((userDoc) => {
      // Get the Array of bookmarks
      var favorites = userDoc.data().favorites;
      console.log(favorites);

      // Iterate through the ARRAY of bookmarked hikes (document ID's)
      favorites.forEach((thisStoreID) => {
        console.log(thisStoreID);
        db.collection("stores")
          .doc(thisStoreID)
          .get()
          .then((doc) => {
            var title = doc.data().name; // get value of the "name" key
            var storeCode = doc.data().code; //get unique ID to each Store to be used for fetching right image
            var storeLocation = doc.data().location; //gets the location field
            var storeStatus = doc.data().status; //gets the store status
            var docID = doc.id; //this is the autogenerated ID of the document

            // Get pointer the new card template
            let newcardTemplate = document.getElementById(
              "favoriteCardTemplate"
            );
            //clone the new card
            let newcard = newcardTemplate.content.cloneNode(true);

            //update title and some pertinant information
            newcard.querySelector(".card-title").innerHTML = title;
            newcard.querySelector(".card-location").innerHTML = storeLocation;
            newcard.querySelector(
              ".card-image"
            ).src = `./images/${storeCode}.jpg`; //Example: NV01.jpg
            newcard.querySelector(".card-status").innerHTML = storeStatus;
            newcard.querySelector("a").href = "eachStore.html?id=" + docID;

            // //NEW LINE: update to display length, duration, last updated
            // newcard.querySelector('.card-status').innerHTML =
            //     "Length: " + doc.data().length + " km <br>" +
            //     "Duration: " + doc.data().hike_time + "min <br>" +
            //     "Last updated: " + doc.data().last_updated.toDate().toLocaleDateString();
            // Finally, attach this new card to the gallery
            storeCardGroup.appendChild(newcard);
          });
      });
    });
}
